controller_list:
  - name: /rt_traj_exe
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - terabot_1_joint
      - terabot_2_joint
      - terabot_5_joint
      - terabot_8_joint
      - terabot_9_joint
      - terabot_91_joint
      - terabot_92_joint
