# Configs the mapping of joints with real devices
# Define the different types of interfaces
types: [ gazebo_position]

groups: { 
 arm_j1: { name: arm_j1, type: gazebo_position, joints: [terabot_1_joint], command_topic: /terabot/j1_position_controller/command},
 arm_j2: { name: arm_j2, type: gazebo_position, joints: [terabot_2_joint], command_topic: /terabot/j2_position_controller/command},
 arm_j3: { name: arm_j3, type: gazebo_position, joints: [terabot_5_joint], command_topic: /terabot/j3_position_controller/command},
 arm_j4: { name: arm_j4, type: gazebo_position, joints: [terabot_8_joint], command_topic: /terabot/j4_position_controller/command},
 arm_j5: { name: arm_j5, type: gazebo_position, joints: [terabot_9_joint], command_topic: /terabot/j5_position_controller/command},
 gripper_j1: { name: gripper_j1, type: gazebo_position, joints: [terabot_91_joint], command_topic: /terabot/jg1_position_controller/command},
 gripper_j2: { name: gripper_j2, type: gazebo_position, joints: [terabot_92_joint], command_topic: /terabot/jg2_position_controller/command}
}
